pipeline
{
    agent any 
    stages 
    {
        stage('Build')
        {
            steps 
            {
                echo "This is Build stage"
            }
        }
        stage('Test')
        {
            steps 
            {
                echo "This is test stage"
            }
        }
        stage('Deploy')
        {
            steps 
            {
                echo "This is deploy stage"
            }
        }
        
    }
}